sonar.projectKey=Escael01_evaluacion3-SDLC
sonar.organization=escael01
sonar.host.url=https://sonarcloud.io

# Carpetas fuente (código real)
sonar.sources=src

# Carpetas de test
sonar.tests=.

# Exclusiones (no analizar dependencias ni coverage)
sonar.exclusions=node_modules/**,coverage/**,dist/**

# Reporte de cobertura generado por Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info
