sonar.projectKey=Escael01_evaluacion3-SDLC
sonar.organization=escael01
sonar.host.url=https://sonarcloud.io
<<<<<<< HEAD
sonar.sources=.
sonar.sourceEncoding=UTF-8
=======
sonar.sourceEncoding=UTF-8

# Donde está tu código
sonar.sources=src

# Donde están tus tests
sonar.tests=.
sonar.test.inclusions=**/*index.test.js

# Reporte de cobertura
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusiones
sonar.exclusions=node_modules/**,coverage/**,dist/**,.github/**
>>>>>>> feature/final-refactor
